---

# Fix absolute paths into relative paths

x-certs: &certs
  - ./certs/root.crt:/certs/nlx-pki-root.crt:ro
  - ./certs/org.crt:/certs/nlx-pki-cert.crt:ro
  - ./certs/org.key:/certs/nlx-pki-key.key:ro
  - ./nlx-try-me/pki/ca/intermediate_ca.pem:/certs/internal-root.crt:ro
  - ./nlx-try-me/pki/certs/internal-cert.pem:/certs/internal-cert.crt:ro
  - ./nlx-try-me/pki/certs/internal-cert-key.pem:/certs/internal-cert.key:ro

services:
  outway:
    volumes: *certs
  inway:
    volumes: *certs
  api:
    volumes: *certs
  postgres:
    image: postgres:12-alpine
